### ISSUE TITLE
Application Deployment 

### ISSUE THREAD

**Issue by tahseenzahra** [tahseenzahra/Portfolio-setup-and-mobile-version-skeleton#13]
The GitHub page link was already created
Here is the link of live Portfolio 
https://tahseenzahra.github.io/Portfolio-setup-and-mobile-version-skeleton/

**Comment by m05e5** [comment]
# Hi @tahseenzahra , 

### Status: Approved ✔️
![goodjob](https://user-images.githubusercontent.com/60631456/130260474-3c2d5e5c-96df-43de-a0db-8d0059c10862.gif)


:+1: You have done all the required changes asked by the previous reviewer. Well Done.

Your project is complete! 
Congratulations! 🎉 


**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
-----

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_m05e5_**

------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
